  const mongoose = require('mongoose');

  const SiteDataSchema = mongoose.Schema
  ({
    sitename:  { type: String, minlength: [4, 'Short sitename'],maxlength: [100, 'Long sitename'],
      default:'Sitename not set', unique: true, ru_label: 'Имя сайта',  input_type: 'text'},
    logo:  { type: String, minlength: [4, 'Short logo'], maxlength: [100, 'Long logo'],
      default:'logo not set', ru_label: 'Лого',  input_type: 'single_image'},
    phone:  { type: String, minlength: [4, 'Short phone'],maxlength: [100, 'Long phone'],
      default:'phone not set', ru_label: 'Телефон',  input_type: 'phone'},
    phone1:  { type: String, minlength: [4, 'Short phone'],maxlength: [100, 'Long phone'],
      default:'phone not set', ru_label: 'Телефон 2',  input_type: 'phone'},
    phone2:  { type: String, minlength: [4, 'Short phone'],maxlength: [100, 'Long phone'],
      default:'phone not set', ru_label: 'Телефон в шапке(синяя полоса)',  input_type: 'phone'},
    mail:  { type: String, minlength: [4, 'Short mail'],maxlength: [100, 'Long mail'],
      default:'mail not set', ru_label: 'Почта',  input_type: 'email'},
    address:  { type: String, minlength: [4, 'Short address'],maxlength: [100, 'Long address'],
      default:'address not set', ru_label: 'Адрес',  input_type: 'text'},
    contacts_page_about_map:  { type: String, minlength: [4, 'Short contacts_page_about_map'],maxlength: [500, 'Long contacts_page_about_map'],
        default:'contacts_page_about_map not set', ru_label: 'Карта (Google maps iFrame)',  input_type: 'link'},
    // fb_link:  { type: String, minlength: [4, 'Short fb_link'],maxlength: [100, 'Long fb_link'],
    //   default:'facebook_link not set', ru_label: 'Ссылка на Facebook',  input_type: 'link'},
    // insta_link:  { type: String, minlength: [4, 'Short insta_link'],maxlength: [100, 'Long insta_link'],
    //   default:'instagram link not set', ru_label: 'Ссылка на Instagram',  input_type: 'link'},
    // twitter_link:  { type: String, minlength: [4, 'Short twitter_link'],maxlength: [100, 'Long twitter_link'],
    //   default:'twitter link not set', ru_label: 'Ссылка на Twitter',  input_type: 'link'},
    // subscribe_heading:  { type: String, minlength: [4, 'Short subscribe_heading'],maxlength: [100, 'Long subscribe_heading'],
    //   default:'subscribe_heading not set', ru_label: 'Подписаться на обновления - заголовок',  input_type: 'text'},
    // subscribe_subheading:  { type: String, minlength: [4, 'Short subscribe_subheading'],maxlength: [100, 'Long subscribe_subheading'],
    //   default:'subscribe_subheading not set', ru_label: 'Подписаться на обновления - подзаголовок',  input_type: 'text'},
    // subscribe_placeholder:  { type: String, minlength: [4, 'Short subscribe_placeholder'],maxlength: [100, 'Long subscribe_placeholder'],
    //   default:'subscribe_placeholder not set', ru_label: 'Подписаться на обновления - надпись на форме',  input_type: 'text'},
    // subscribe_data_error:  { type: String, minlength: [4, 'Short subscribe_data_error'],maxlength: [100, 'Long subscribe_data_error'],
    //   default:'subscribe_data_error not set', ru_label: 'Подписаться на обновления - ошибка заполнения формы',  input_type: 'text'},
    // subscribe_text:  { type: String, minlength: [4, 'Short subscribe_text'],maxlength: [100, 'Long subscribe_text'],
    //   default:'subscribe_text not set', ru_label: 'Подписаться на обновления - текст на кнопке',  input_type: 'text'},
    // weekly_offer_heading:  { type: String, minlength: [4, 'Short weekly_offer_heading'],maxlength: [100, 'Long weekly_offer_heading'],
    //   default:'weekly_offer_heading not set', ru_label: 'Предложение недели - заголовок',  input_type: 'text'},
    // weekly_offer_background:  { type: String, minlength: [4, 'Short weekly_offer_background'],maxlength: [100, 'Long weekly_offer_background'],
    //   default:'weekly_offer_background not set', ru_label: 'Предложение недели - Фото',  input_type: 'single_image'},
    // weekly_offer_prize:  { type: String, minlength: [4, 'Short weekly_offer_prize'],maxlength: [100, 'Long weekly_offer_prize'],
    //   default:'weekly_offer_prize not set', ru_label: 'Предложение недели - Иконка',  input_type: 'single_image'},
    // footer_description:  { type: String, minlength: [4, 'Short footer_description'],maxlength: [500, 'Long footer_description'],
    //   default:'footer_description not set', ru_label: 'Футер - описание',  input_type: 'text'},
    // new_houses_background:  { type: String, minlength: [4, 'Short new_houses_background'],maxlength: [100, 'Long new_houses_background'],
    //   default:'new_houses_background not set', ru_label: 'Строящиеся дома - Фон',  input_type: 'single_image'},
    // new_houses_title:  { type: String, minlength: [4, 'Short new_houses_title'],maxlength: [500, 'Long new_houses_title'],
    //   default:'new_houses_title not set', ru_label: 'Строящиеся дома - описание',  input_type: 'text'},
    // old_houses_title:  { type: String, minlength: [4, 'Short old_houses_title'],maxlength: [500, 'Long old_houses_title'],
    //   default:'old_houses_title not set', ru_label: 'Сданные дома  - фон',  input_type: 'text'},
    // old_houses_background:  { type: String, minlength: [4, 'Short old_houses_background'],maxlength: [500, 'Long old_houses_background'],
    //     default:'old_houses_background not set', ru_label: 'Сданные дома  - - описание',  input_type: 'single_image'},
    //   offices_page_title:  { type: String, minlength: [4, 'Short prices_page_title'],maxlength: [500, 'Long prices_page_title'],
    //     default:'Офисы', ru_label: 'Страница Офисы - заголовок',  input_type: 'text'},
    //   offices_page_background:  { type: String, minlength: [4, 'Short prices_page_background'],maxlength: [500, 'Long prices_page_background'],
    //     default:'prices_page_background not set', ru_label: 'Страница Офисы - фон',  input_type: 'single_image'},
    //   about_page_title:  { type: String, minlength: [4, 'Short about_page_title'],maxlength: [500, 'Long about_page_title'],
    //     default:'about_page_title not set', ru_label: 'Страница О нас - заголовок',  input_type: 'text'},
    //   about_page_subtitle:  { type: String, minlength: [4, 'Short about_page_subtitle'],maxlength: [500, 'Long about_page_subtitle'],
    //     default:'about_page_subtitle not set', ru_label: 'Страница О нас - подзаголовок',  input_type: 'text'},
    //   about_page_desc:  { type: String, minlength: [4, 'Short about_page_desc'],maxlength: [6500, 'Long about_page_desc'],
    //     default:'about_page_desc not set', ru_label: 'Страница О нас - описание',  input_type: 'text'},
    //   about_page_desc1:  { type: String, minlength: [4, 'Short about_page_desc'],maxlength: [6500, 'Long about_page_desc'],
    //     default:'about_page_desc not set', ru_label: 'Страница О нас - описание',  input_type: 'text'},
    //   about_page_desc2:  { type: String, minlength: [4, 'Short about_page_desc'],maxlength: [6500, 'Long about_page_desc'],
    //     default:'about_page_desc not set', ru_label: 'Страница О нас - описание',  input_type: 'text'},
    //   // about_page_background:  { type: String, minlength: [4, 'Short about_page_background'],maxlength: [500, 'Long about_page_background'],
    //   //   default:'about_page_background not set', ru_label: 'Страница О нас  - фон',  input_type: 'single_image'},
    //   // about_page_side_image:  { type: String, minlength: [4, 'Short about_page_side_image'],maxlength: [500, 'Long about_page_side_image'],
    //   //   default:'about_page_side_image not set', ru_label: 'Страница О нас  - Изображение возле текста о компании',  input_type: 'single_image'},
    //   contacts_page_title:  { type: String, minlength: [4, 'Short contacts_page_title'],maxlength: [500, 'Long contacts_page_title'],
    //     default:'contacts_page_title not set', ru_label: 'Страница Контакты - Заголовок',  input_type: 'text'},
    //   contacts_page_form_title:  { type: String, minlength: [4, 'Short contacts_page_form_title'],maxlength: [500, 'Long contacts_page_form_title'],
    //     default:'contacts_page_form_title not set', ru_label: 'Страница Контакты - Заголовок формы',  input_type: 'text'},
    //   contacts_page_contact_title:  { type: String, minlength: [4, 'Short contacts_page_contact_title'],maxlength: [500, 'Long contacts_page_contact_title'],
    //     default:'contacts_page_contact_title not set', ru_label: 'Страница Контакты - Заголовок контактных данных',  input_type: 'text'},
    //   contacts_page_about_title:  { type: String, minlength: [4, 'Short contacts_page_about_title'],maxlength: [500, 'Long contacts_page_about_title'],
    //     default:'contacts_page_about_title not set', ru_label: 'Страница Контакты - Заголовок параграфа',  input_type: 'text'},
    //   contacts_page_about_desc:  { type: String, minlength: [4, 'Short contacts_page_about_desc'],maxlength: [500, 'Long contacts_page_about_desc'],
    //     default:'contacts_page_about_desc not set', ru_label: 'Страница Контакты - Описание',  input_type: 'text'},

  }, {
      timestamps: true
  });

  module.exports = mongoose.model('SiteData', SiteDataSchema);
